# Generated by Django 2.2.10 on 2020-11-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('CHC', 'Выбрать один вариант'), ('CHS', 'Выбрать несколько вариантов'), ('TXT', 'Ответ текстом')], default='CHC', max_length=3, verbose_name='тип вопроса'),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default=None, verbose_name='текст вопроса'),
            preserve_default=False,
        ),
    ]
