# Generated by Django 2.2.10 on 2020-11-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201103_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='активный'),
        ),
    ]
