# Generated by Django 2.2.10 on 2020-11-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_poll_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True, verbose_name='текстовый ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ManyToManyField(blank=True, related_name='answers', to='polls.Choice'),
        ),
    ]
