# Generated by Django 2.2.10 on 2020-11-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20201103_2036'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('user_id', 'question')},
        ),
    ]
